remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
title: Pokemon Community Game Bot
description: Monitor Pokemon spawns in Twitch chat and send them to your Discord server!
show_downloads: false
