name: Deploy Website

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Build site
      run: |
        cd docs
        bundle install
        bundle exec jekyll build

    - name: Deploy
      uses: actions/upload-artifact@v4
      with:
        name: github-pages
        path: docs/_site
        if-no-files-found: error
        retention-days: 1
