name: Deploy Bot and Website

on:
  push:
    branches: [ main ]

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
    
    - name: Build site
      run: |
        cd docs
        bundle config set --local path 'vendor/bundle'
        bundle install
        bundle exec jekyll build
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_site

  deploy-bot:
    runs-on: ubuntu-latest
    environment: Production
    needs: deploy-site
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create env file
      run: |
        echo "DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }}" >> .env
        echo "TWITCH_TOKEN=${{ secrets.TWITCH_TOKEN }}" >> .env
        echo "DISCORD_CLIENT_ID=${{ secrets.DISCORD_CLIENT_ID }}" >> .env
        echo "DISCORD_CHANNEL_ID=${{ secrets.DISCORD_CHANNEL_ID }}" >> .env
        echo "DISCORD_GUILD_ID=${{ secrets.DISCORD_GUILD_ID }}" >> .env
        echo "TWITCH_MONITOR_CHANNEL=${{ secrets.TWITCH_MONITOR_CHANNEL }}" >> .env
    
    - name: Run bot
      run: |
        python pokemon.py
